#!/bin/bash 
declare -a vot2015=(bag ball1 ball2 basketball birds1 birds2 blanket bmx bolt1 bolt2 book butterfly car1 car2 crossing dinosaur fernando fish1 fish2 fish3 fish4 girl glove godfather graduate gymnastics1 gymnastics2 gymnastics3 gymnastics4 hand handball1 handball2 helicopter iceskater1 iceskater2 leaves marching matrix motocross1 motocross2 nature octopus pedestrian1 pedestrian2 rabbit racing road shaking sheep singer1 singer2 singer3 soccer1 soccer2 soldier sphere tiger traffic tunnel wiper)
echo "Testing ${#vot2015[@]} datasets"
for i in "${vot2015[@]}"
do
  echo "Testing element \"$i\" with pmmh:"
  /bin/bash $PWD/../scripts/test_dataset 2015 $i pmmh
  echo "Testing element \"$i\" with tracker:"
  /bin/bash $PWD/../scripts/test_dataset 2015 $i tracker
done
